[package]
name = "osrm_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.122"
strum = { version = "0.26.3", features = ["derive", "strum_macros"] }
